spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.184.128}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:aloha_admin}?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      maximumPoolSize: 30
      minimumIdle: 10
# 生产环境不需要
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 是否控制台打印mybatis-plus的LOGO
  global-config:
    banner: false